### PR TITLE
UI vue loader fix

### LINKED ISSUE #225: Interface is a reserved keyword
Because interface is a reserved keyword the Vue JS loader cannot load the topology UI.

### PR DESCRIPTION
**Pull request by HeriLFIU**
Closes #225 

### Summary

Interface was a reserved keyword and it would not be loaded by the Vue JS loader. Because of this `interface` was replaced with `k_interface`.

### Local Tests

Changes didn't seem to affect UI as they were just a variable name change.

### CODE REVIEW

**Review by viniarck — APPROVED** [review]
Looks good to me @HeriLFIU. This doesn't need changelog updatd since it's just equivalent refactoring. Another benefit of not using `interface` as a var name is that if one day we evolve the codebase to use TypeScript then it's another less conflict. 

@HeriLFIU, by grepping in the code `maintenance` I found another [`interface` var](https://github.com/kytos-ng/maintenance/blob/master/ui/k-info-panel/edit_window.kytos#L267), if it's not on your radar yet, you might want to double check it.

**Comment by HeriLFIU** [comment]
@viniarck oh ya, thanks, I just noticed it while trying to load maintenance. I just finished refactoring all k-toolbars that had issues, so now Imma try and load in all of the k-info-panels.

**Review by rmotitsuki — APPROVED** [review]
LGTM. Great work!

**Comment by viniarck** [comment]
Let's ship it.

**Pull request merged**
